
CREATE TABLE tblGender
(
  ID INT PRIMARY KEY NOT NULL,
  Gender NVARCHAR(50) NOT NULL
)

CREATE TABLE tblPerson
(
  ID INT PRIMARY KEY NOT NULL,
  Name NVARCHAR(50) NOT NULL,
  Email NVARCHAR(50) NOT NULL,
  GenderId INT NULL
)  

ALTER TABLE tblPerson ADD CONSTRAINT tblPerson_GenderID_FK FOREIGN KEY (GenderId) REFERENCES tblGender(ID)